services:
  - type: web
    name: evently-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
      - key: PORT
        value: 3000
      - key: API_PREFIX
        value: /api
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: DATABASE_URL
        fromDatabase:
          name: evently-db
          property: connectionString
      - key: RATE_LIMIT_WINDOW_MS
        value: 15 * 60 * 1000
      - key: RATE_LIMIT_MAX
        value: 100
      - key: LOG_LEVEL
        value: info

databases:
  - name: evently-db
    plan: free
    ipAllowList: [] # allow all connections
